Cassandane/Cyrus/Metadata.pm

`/vendor/cmu/cyrus-imapd/archive` and `/vendor/cmu/cyrus-imapd/delete` are the
new annotations in `cyrus-imapd`.

[Metadata] Include new annotations in tests.

---

Cassandane/Cyrus/Archive.pm
Cassandane/Cyrus/Delete.pm

Tests for:
* archvive
* delete

Tests for `cyr_expire`.

---

Cassandane/Cyrus/Annotator.pm

Changes made by annotator via xrunannotator weren't immediately
visible[1]. This test ensures that the fix is in place.
[1] issue https://github.com/cyrusimap/cyrus-imapd/issues/2071

[Annotator] xrunannotor doesn't bump modseq.

---

Cassandane/Cyrus/Autocreate.pm

The `autocreate_sieve` function creats a compiled sieve script. This
test ensures that those files exist.

[Autocreate] Ensure sieve scripts exists.

---

Cassandane/Instance.pm

In some cases, run_command() would fork using a pipe:
my $pid = open $fh,'|-';
die "Cannot fork: $!"
if !defined $pid;
if ($pid)
{
$self->_add_child($binary, $pid, $options->{handlers}, $fh);
print $fh ${$data};
close ($fh);
return $pid;
}
The problem is, the close ($fh) there waits for the child to exit,
which means later in reap_command(), waitpid($pid, 0) returns -1
since there are no children, and our caller gets back undef.
This fixes that by returning the child status if we know we already
have one and bypassing reap_command() entirely.
Solves #52

Return an exit status even if we fork using a filehandle

---

Cassandane/Cyrus/TesterJMAP.pm

Otherwise fuzzy searching doesn't work

Run squatter in rolling indexer mode for Email/query text searches

---

Cassandane/Cyrus/FastMail.pm
Cyrus/IndexFile.pm

The pair for the change to Cyrus

Sync rename delete safety

---

Cassandane/Cyrus/JMAPEmail.pm

See https://github.com/cyrusimap/cyrus-imapd/pull/3259

JMAPEmail: add test for foo@*.com email wildcard query

---

Cassandane/Cyrus/JMAPEmail.pm

See https://github.com/cyrusimap/cyrus-imapd/pull/3260

test the addseen failure bug

---

Cassandane/Cyrus/Sieve.pm

This tests https://github.com/cyrusimap/cyrus-imapd/pull/3257

Sieve.pm : added test_editheader_encoded_address_list

---

Cassandane/Cyrus/JMAPEmail.pm

https://github.com/cyrusimap/cyrus-imapd/pull/3306 got merged on master

JMAPEmail: return AttachmentMatch in SearchSnippet/get

---

Cassandane/Cyrus/JMAPEmail.pm

https://github.com/cyrusimap/cyrus-imapd/pull/3304 got merged on master

JMAPEmail: support substring search in email headers

---

Cassandane/Cyrus/JMAPEmail.pm

https://github.com/cyrusimap/cyrus-imapd/pull/3308 got merged on master

JMAPEmail: rewrite email query folder-search optimizer to use DNF

---

Cassandane/Cyrus/Bug3470.pm
Cassandane/Cyrus/Create.pm
Cassandane/Cyrus/FastMail.pm
Cassandane/Cyrus/JMAPMailbox.pm
Cassandane/Cyrus/List.pm
Cassandane/Cyrus/Prometheus.pm
Cassandane/Cyrus/Rename.pm

For testing https://github.com/cyrusimap/cyrus-imapd/pull/3447

Create no intermediates

---

Cassandane/Cyrus/JMAPEmail.pm

For testing https://github.com/cyrusimap/cyrus-imapd/pull/3450

JMAPEmail.pm: fixes for split attachment filenames

---

Cassandane/Cyrus/JMAPCalendars.pm
Cassandane/Cyrus/JMAPContacts.pm

For testing https://github.com/cyrusimap/cyrus-imapd/pull/3448

Jmap shared upload collection

---

Cassandane/Cyrus/JMAPContacts.pm

For testing https://github.com/cyrusimap/cyrus-imapd/pull/3459

Added test_contact_apple_label_handling

---

Cassandane/Cyrus/JMAPCalendars.pm

For testing https://github.com/cyrusimap/cyrus-imapd/pull/3474

JMAPCalendars.pm: make sure unshared account is removed from JMAP session object

---

Cassandane/Cyrus/JMAPEmail.pm
Cassandane/Cyrus/TestCase.pm

The related branch on cyrus-imapd is merged now :)

JMAPEmail: replace Email/query on-disk cache with in-memory

---

Cassandane/Cyrus/JMAPCalendars.pm

This is merged on cyrus-imapd now

Jmap calendarevent organizeronly attendeeonly

---

Cassandane/Cyrus/JMAPEmail.pm

Tests https://github.com/cyrusimap/cyrus-imapd/pull/3524

JMAPEmail: fix 'hasKeyword:$seen' queries for shared mailboxes

---

Cassandane/Cyrus/Caldav.pm

This tests a busytime query via a POST to Outbox.
This also tests case-insensitive check of "mailto" in CUAs when PUTting a scheduling resource

Caldav.pm: add test_sched_busytime_query

---

Cassandane/Cyrus/Replication.pm

Tests for https://github.com/cyrusimap/cyrus-imapd/pull/3608

Replication: test empty and non-empty mailbox overwrite

---

Cassandane/Cyrus/Simple.pm

Test for https://github.com/cyrusimap/cyrus-imapd/pull/3602

Simple: test for sessionid in cmdtimer output

---

Cassandane/Instance.pm

Needs https://github.com/cyrusimap/cyrus-imapd/pull/3645 to be applied for this to pass!

reconstruct: use -G so we re-parse the message too

---

Cassandane/Util/Log.pm

xlog: fix sub and line calculation

---

Cassandane/Cyrus/JMAPCalendars.pm

There are reports that https://github.com/cyrusimap/cyrus-imapd/commit/c5c592b9f335511ab2488d0cf81545d0bb14d2ac introduced a bug where the `timeZone` property may include the libical BUILTIN_TZID_PREFIX value in notifications. This patch updates the test to also check for notifications.

JMAPCalendars: assert Cyrus IANA timezones also in notifications

---

Cassandane/Cyrus/Sieve.pm

And added another similar test that I had lying around on a branch but had clearly forgotten about!

some Sieve tests need updates for long subject folding/encoding changes

---

Cassandane/Cyrus/MurderIMAP.pm

Tests for https://github.com/cyrusimap/cyrus-imapd/pull/3706

make sure XFER doesn't create intermediates in user tree
