Cassandane/Cyrus/Sieve.pm
This is the corresponding Cassandane test for the new compile-sieve-on-demand feature that https://github.com/cyrusimap/cyrus-imapd/pull/13 adds to lmtpd
=> Sieve: test delivery when compiled bytecode is missing

Cassandane/Cyrus/Fetch.pm
This patch adds support to test the `FETCH` changes made to
`index_fetch` to single-pass inline unsolicited FETCHes.
This is a test to fix https://github.com/cyrusimap/cyrus-imapd/issues/1971.
=> Fetch: Test to tell EXISTS count earlier.

Cassandane/Cyrus/Idle.pm
By setting the timeout to 60 seconds(which is the timeout if
`imapidlepoll` isn't set in the `imapd.conf` and ensure that `idled`
responds immediately, we make sure that `idled` is working as expected.
This test fails if the response takes longer than 5 seconds, it is a
problem when running on slow machines. Will bump the 5 second time based
on how the test works on CI.
=> [Idle] Enssure idled is working as expected.

Cassandane/Cyrus/Idle.pm
Running the detault timeout test in a docker container fails because the
test takes longer to run. Bumping the timeout for the test
`idled_default_timeout` to `15 seconds` from the current `5 seconds`.
=> [Idle] Increase time tolerance for timeout test.

COPYRIGHT, Cassandane/Instance.pm, Cassandane/Net/SMTPServer.pm, Cassandane/PortManager.pm, Net/README, Net/XmtpServer.pm
_Please don't merge this PR if you are OK with it. I'll need to update Cyrus master first._
We want to migrate the Cyrus-internal sendmail code to use SMTP backends. But this requires us to sandbox SMTP requests within Cassandane, otherwise we risk testers to unintentionally send out spam.
This PR adds a dummy SMTP server to Cassandane using the following approach:
- Cassandane::Instance::start calls an internal method _start_smtpd, which
is similar to _start_notifyd and the like.
- _start_smtpd forks the current process, launches the SMTPServer and tells it
to auto-assign a TCP port using port number 0. The child process then writes
back the auto-allocated TCP port number on a pipe to the master Cassandane
process, which sets up the imapd.conf parameters accordingly.
- The master process …
=> Sandbox SMTP email submissions in Cassandane

Cassandane/Cyrus/TesterJMAP.pm
Also, if the AUTHOR_TESTING environment variable is set, look in xt/
With this, test specification changes slightly:
Instead of:
TesterJMAP.previews
You'd do:
TesterJMAP.t:previews
(providing paths with / replaced with :)
=> TesterJMAP: Recurse to find tests in t/ of JMAP::TestSuite

Cassandane/Cyrus/TesterJMAP.pm
This includes:
* Test output (from ok(), etc)
* JMAP::Tester::Logger output about requests/responses to cyrus
=> Instruct JMAP::TestSuite to include more info in verbose mode

Cassandane/BuildInfo.pm, Cassandane/Cyrus/Autocreate.pm, Cassandane/Cyrus/CaldavAlarm.pm, Cassandane/Cyrus/ClamAV.pm, Cassandane/Cyrus/JMAPCalendars.pm, Cassandane/Cyrus/JMAPContacts.pm, Cassandane/Cyrus/JMAPCore.pm, Cassandane/Cyrus/JMAPMail.pm, Cassandane/Cyrus/Replication.pm, Cassandane/Cyrus/SearchFuzzy.pm, Cassandane/Cyrus/Sieve.pm, Cassandane/Cyrus/TestCase.pm, Cassandane/Cyrus/TesterJMAP.pm, Cassandane/Instance.pm, Cassandane/Unit/TestCase.pm, testrunner.pl
Putting this in as a PR mainly to make sure it doesn't break for @jasontibbitts before I merge it down.
=> Add :needs_foo_bar attribute for marking tests as dependent on optional features

Cassandane/Unit/TestPlan.pm
This makes it so you can copy the test spec from the test
output and use it directly to run that single test.
Previously, you'd have to copy only the TesterJMAP portion and
use that.
That is, this now works:
./testrunner.pl -f pretty Cyrus::TesterJMAP
=> Allow using Cyrus::TesterJMAP as a test spec

Cassandane/Cyrus/JMAPCalendars.pm
Most clients can't handle this and will refuse to show events
=> Add test to ensure rscale is hidden from caldav if added in JMAP

Cassandane/Cyrus/JMAPTestSuite.pm
These get filled in anyway for us and they stay around
after a test run so that you can look at the raw data.
By using tempdir(), we were mistakenly cleaning up these
directories after each test run. Oops.
=> JMAPTestSuite: Don't override search/data partitions

Cassandane/Cyrus/FastMail.pm
Tests for rename safety after the INBOX.INBOX.INBOX shenanigans.
Aligned with https://github.com/cyrusimap/cyrus-imapd/pull/3253
=> Jmap name safety

Cassandane/Cyrus/Metadata.pm, Cassandane/Cyrus/Rename.pm, Cassandane/Cyrus/Replication.pm, Cassandane/Cyrus/TestCase.pm
This is the tests for the related issue that I'm about to post an MR for.  Replication of server-level annotations wasn't working.  Also, this set of tests found a permissions bug for shared arbitrary annotations: https://github.com/cyrusimap/cyrus-imapd/pull/3456
=> Server annotation replication

Cassandane/Cyrus/CaldavAlarm.pm
This is long enough to make sure slow valgrind doesn't break them.  We were seeing spurious errors otherwise under valgrind.
=> CaldavAlarm: run all tests 300s in the future

Cassandane/Cyrus/Replication.pm, Cassandane/Cyrus/TestCase.pm, Cassandane/Instance.pm
* clean up properly after Instance::_check_sanity() finds errors (prevents later tests from failing due to port conflicts)
* _check_sanity() does nothing if the instance's Cyrus is older than 3.5
* fixed the version check in run_mbpath() to check the correct Cyrus
* fixed some missing :min_version_3_5's
=> fixes for problems found while testing 3.4

Cassandane/Config.pm, Cassandane/Instance.pm, Cassandane/Test/Config.pm
This will let us treat 'httpmodules' et al as the set of flags it is, rather than an opaque string.
Need this for some refactoring I have planned for #151, but splitting it out so it can be reviewed separately
=> Config: add understanding of imapd.conf BITFIELDs

Cassandane/Cyrus/Metadata.pm, Cassandane/Cyrus/Rename.pm, Cassandane/Cyrus/SearchFuzzy.pm, Cassandane/Instance.pm
This was SUPPOSED to be a small metadata test, and turned into realising that all of the Metadata tests weren't actually working correctly, because list_annotations wasn't doing what it said on the tin for two separate bugs - but comparing the replication still got us zero / zero annotations, which funnily enough passed the tests.
Doing things this way gives us a much more powerful ability to manipulate database files.
=> Add run_dbcommand logic ported from Fastmail code

Cassandane/Cyrus/FastMail.pm
This tests the new commits that have been added to https://github.com/cyrusimap/cyrus-imapd/pull/3522 to make sure the correct uniqueid vs mailbox name are used for conversations db updates on mailbox rename and delete.
=> Check search deleted folders

Cassandane/Cyrus/Rename.pm
As requested in https://github.com/cyrusimap/cyrus-imapd/pull/3650
=> rename_inbox: check that INBOX mailboxid doesn't change

Cassandane/Cyrus/Rename.pm
This only affected pre-3.5 tests so it slipped under the radar!
=> Rename: fix typo

Cassandane/Cyrus/JMAPCore.pm, Cassandane/Cyrus/Murder.pm, Cassandane/Cyrus/MurderIMAP.pm, Cassandane/Cyrus/MurderJMAP.pm, Cassandane/Cyrus/TestCase.pm, Cassandane/Cyrus/TesterCalDAV.pm, Cassandane/Cyrus/TesterCardDAV.pm
This is for https://github.com/cyrusimap/cyrus-imapd/pull/3564
We have a small handful of very basic tests for murder setups (Murder.pm), but the way we set things up in Cassandane meant these could only use IMAP.
This PR adjusts the infrastructure so that a test can _either_ require an IMAP murder or a JMAP murder (but not both!), modifies the existing Murder.pm tests to use the new infrastructure, and adds a couple of basic JMAP tests too.
We can and should add more tests to this, but so far this proves that the basic premise -- connecting to the frontend, making a JMAP request, and the request being proxied to the backend containing the user's account -- seems to work.
There's probably more to do with the infrastructure yet, but I won't be sure what it needs to look like until we write …
=> Add support for testing JMAP in a murder setup

Cassandane/Cyrus/TestCase.pm
This allows run with `-v -v` to spit out JMAP traffic.
=> re-add DEBUGJMAP (removed in cf7d0c6c11ec3b5e437697a74249395a2cfff8a0)

Cassandane/Cyrus/List.pm, Cassandane/Cyrus/TestCase.pm, Cassandane/Instance.pm
This adds two tests:
* List.no_tombstones: make sure tombstones for regular mailboxes aren't included in LIST or XLIST results
* List.no_inbox_tombstone: make sure a tombstone for an INBOX isn't included in LIST or XLIST results
The latter exposes a bug in 2.5.  Otherwise, these are just regression tests.
It also adds `setup_mailbox_structure()` and `assert_mailbox_structure()` methods to TestCase, where they can be used by other suites -- they were previously internal to the List suite.  This doesn't help us immediately, but I already have a couple of other WIP branches that depend on this commit, so it would be nice to get it upstream where I no longer have to juggle it around.
Edit: oh, and it also adds a `read_mailboxes_db()` method to Instance, which is needed for these tests, and …
=> make sure LIST/XLIST don't return tombstones

Cassandane/Cyrus/MurderIMAP.pm, Cassandane/Cyrus/Pop3.pm, Cassandane/IMAPMessageStore.pm
This adds a bunch of tests for XFER of a user, and one test for XFER of a single mailbox.  These tests are for the fixes in https://github.com/cyrusimap/cyrus-imapd/pull/3693
The XFER user tests are fairly exhaustive, because that was my focus.  They are all `:min_version_3_2` because an unrelated behaviour changed in 3.2 (implied `RETURN (SPECIAL-USE)` in LIST), and so as written the tests don't pass on 3.0.  They can be tinkered with to prove the fixes work for 3.0 as well, but I didn't feel like duplicating them just for that.
The XFER mailbox test is singular for now, just to make sure nothing unexpected broke.  It is `:max_version_3_4` because it turns out 3.5 can create an intermediate on this code path, which is bad!  That'll need fixing separately, so it'll get a test case …
=> Tests for XFER of user and mailbox

Cassandane/Cyrus/JMAPTestSuite.pm, Cassandane/Cyrus/JMAPTestSuiteWS.pm
Currently, you can run the JMAP-TestSuite tests either using websockets, or not using websockets, by setting the JMTS_USE_WEBSOCKETS environment variable to control its behaviour.  But this means to exercise both variants, you need to run Cassandane twice.
This PR duplicates the existing JMAPTestSuite suite, as JMAPTestSuiteWS.  The original JMAPTestSuite now overrides the environment to ensure websockets are not used, and the new JMAPTestSuiteWS overrides the environment to make sure they are.
JMAPTestSuiteWS checks for the availability of JMAP::Tester::WebSocket, and only enables its tests if it's available.  So if you don't presently have JMAP::Tester::WebSocket installed (like I didn't) it won't blow up in your face, JMAPTestSuiteWS just won't run any tests.  Or, more precisely, it …
=> Run JMAP-TestSuite both with websockets and without

Cassandane/Cyrus/Caldav.pm, Cassandane/Cyrus/JMAPEmail.pm
These changes (plus backporting a couple of Cyrus fixes) fix the current test failures for 3.2 and 3.4
=> fixes for Caldav/JMAPEmail failures on 3.2 and 3.4

Cassandane/Cyrus/TestCase.pm, Cassandane/Instance.pm, Cassandane/Test/Core.pm
We keep having problems where errors detected during `Cassandane::Instance::stop()` lead to the test not being cleaned up properly, which then causes cascading failures later due to cassandane's 91xx ports still being in use by processes left behind by earlier tests.
This fixes the problem by carefully removing all the cases where `stop()` could die, and instead collecting those errors into an array that's returned to the caller.
If one of the instances' `stop()`s manages to die somehow anyway, `Cassandane::Cyrus::TestCase::tear_down()` evals and ignores it, and continues cleaning up anyway.  The first error that was returned by `stop()` is used for the eventual die message.
I have tested this for the specific case of "Errors found in syslog", by temporarily building a cyrus where imapd …
=> Better cleanup after errors during instance shutdown
